"""added priority and description fields

Revision ID: 2415277b5193
Revises: a944b29e9dc3
Create Date: 2024-04-22 17:05:36.790910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2415277b5193'
down_revision = 'a944b29e9dc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracker_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracker_activities', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
