"""added update datetime field

Revision ID: 61cb577a869e
Revises: b7509bae6ed4
Create Date: 2024-04-27 07:01:21.972379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61cb577a869e'
down_revision = 'b7509bae6ed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracker_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracker_tasks', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
