"""delete progress model and added progress field to the task model

Revision ID: 6a578c1ea2e2
Revises: e4f0040a01b3
Create Date: 2024-04-22 22:05:43.326048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a578c1ea2e2'
down_revision = 'e4f0040a01b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracker_task_progresses')
    with op.batch_alter_table('tracker_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracker_tasks', schema=None) as batch_op:
        batch_op.drop_column('progress')

    op.create_table('tracker_task_progresses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tracker_tasks.id'], name='tracker_task_progresses_task_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tracker_task_progresses_pkey')
    )
    # ### end Alembic commands ###
