"""added alive until field and removed life_span_days

Revision ID: 84d9ca023332
Revises: d63d70f94731
Create Date: 2024-04-29 05:39:57.202606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d9ca023332'
down_revision = 'd63d70f94731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracker_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alive_until', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('life_span_days')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracker_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('life_span_days', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('alive_until')

    # ### end Alembic commands ###
