"""added finish datetime field

Revision ID: b7509bae6ed4
Revises: 6a578c1ea2e2
Create Date: 2024-04-27 06:24:44.640794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7509bae6ed4'
down_revision = '6a578c1ea2e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracker_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracker_activities', schema=None) as batch_op:
        batch_op.drop_column('finished_at')

    # ### end Alembic commands ###
