"""added progress field

Revision ID: e4f0040a01b3
Revises: 2415277b5193
Create Date: 2024-04-22 21:27:23.652068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f0040a01b3'
down_revision = '2415277b5193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracker_task_progresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracker_task_progresses', schema=None) as batch_op:
        batch_op.drop_column('progress')

    # ### end Alembic commands ###
